name: Convert IMG to LXC Template (pve)

on:
  workflow_dispatch:
    inputs:
      img_url:
        description: 'IMG下载地址'
        required: true
      tar_name:
        description: 'CT模版文件名称'
        required: true

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-utils lxc rsync tar

    - name: Download the .img file
      run: |
        # Set up the working directory
        mkdir -p ./workspace && cd ./workspace
        # Download the .img file from the input URL
        wget "${{ github.event.inputs.img_url }}" -O system.img.gz
        # Extract the. gz file to obtain the. img file
        zcat system.img.gz > system.img || true

    - name: Convert .img to LXC template
      run: |
        # Mount the .img file
        sudo mkdir /mnt/img
        sudo modprobe nbd max_part=8
        # Specify the image format explicitly as 'raw'
        sudo qemu-nbd -f raw --connect=/dev/nbd0 ./workspace/system.img
        sudo partprobe /dev/nbd0
        
        # Mount the partition (assume it's the first partition)
        sudo mount /dev/nbd0p1 /mnt/img
        
        # Create LXC container rootfs directory
        sudo mkdir -p /var/lib/lxc/container/rootfs
        
        # Copy the image content into the LXC container rootfs
        sudo rsync -a /mnt/img/ /var/lib/lxc/container/rootfs/
        
        # Create basic LXC config file
        sudo tee /var/lib/lxc/container/config <<EOL
        lxc.uts.name = ${{ github.event.inputs.tar_name }}
        lxc.tty.max = 4
        lxc.autodev = 1
        lxc.pty.max = 1024
        lxc.start.auto = 0
        lxc.init.cmd = /sbin/init
        lxc.mount.auto = proc:rw sys:rw
        lxc.rootfs.path = dir:/var/lib/lxc/container/rootfs
        EOL

        # Unmount and clean up
        sudo umount /mnt/img
        sudo qemu-nbd --disconnect /dev/nbd0
        sudo rmdir /mnt/img

    - name: Pack the LXC template into a tar.gz
      run: |
        # Pack the LXC container into a tar.gz file without cd
        sudo tar -czvf "/var/lib/lxc/${{ github.event.inputs.tar_name }}.tar.gz" -C /var/lib/lxc container/*
        # Move the tar.gz to the workspace for GitHub Actions to access
        sudo mv "/var/lib/lxc/${{ github.event.inputs.tar_name }}.tar.gz" $GITHUB_WORKSPACE

    - name: Change ownership or permissions
      run: |
        # Change ownership to the current user
        sudo chown $USER:$USER /var/lib/lxc/${{ github.event.inputs.tar_name }}.tar.gz
        
        # Alternatively, make it readable to all users
        sudo chmod 644 /var/lib/lxc/${{ github.event.inputs.tar_name }}.tar.gz

    - name: Move LXC template to workspace
      run: |
        sudo mv /var/lib/lxc/${{ github.event.inputs.tar_name }}.tar.gz $GITHUB_WORKSPACE/

    - name: Upload LXC template as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.inputs.tar_name }}
        path: $GITHUB_WORKSPACE/${{ github.event.inputs.tar_name }}.tar.gz
        if-no-files-found: warn
        include-hidden-files: false
