name: Convert IMG to LXC Template (pve)

on:
  workflow_dispatch:
    inputs:
      img_url:
        description: 'IMG下载地址'
        required: true
      tar_name:
        description: 'CT模版文件名称'
        required: true
      partition:
        description: '需挂载的分区'
        required: true

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-utils lxc rsync tar

    - name: Download the .img file
      run: |
        # Set up the working directory
        mkdir -p workspace && cd workspace
        # Download the .img file from the input URL
        wget "${{ github.event.inputs.img_url }}" -O system.img.gz
        # Extract the. gz file to obtain the. img file
        gzip -d system.img.gz || true && mv *.img system.img

    - name: Convert .img to LXC template
      run: |
        # Enter working directory
        cd workspace
        # Loading nbd
        modprobe nbd
        # Specify the image format explicitly as 'raw'
        qemu-nbd -c /dev/nbd0 -f raw ./workspace/system.img
        # Mount the .img file
        mkdir /mnt/img && mount /dev/${{ github.event.inputs.partition }} /mnt/img
        # Echo mount
        lsblk -f /dev/nbd0
        echo ls -lh /mnt/img
        # Pack CT Template the .tar.gz file
        tar -czvf $GITHUB_WORKSPACE/${{ github.event.inputs.tar_name }}.tar.gz -C /mnt/img/*
        # Echo .tar.gz file
        ls -lh $GITHUB_WORKSPACE/${{ github.event.inputs.tar_name }}.tar.gz
        
    - name: Upload LXC template as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.inputs.tar_name }}
        path: ${{ github.event.inputs.tar_name }}.tar.gz
